### ISSUE TITLE
issueベースの開発：レビュー依頼

### ISSUE THREAD

**Issue by HIGASHI-SHIHO-54B** [HIGASHI-SHIHO-54B/my-my-project#34]
■Webアプリの概要
ユーフォーキャッチャーで獲得したグッズを、獲得にかかった金額や店舗別に登録できるサービスです。これにより、獲得難易度が高い店舗を可視化し、どれだけお金を使ったかを把握することで、使い過ぎを防ぐことができます。私はユーフォーキャッチャーが好きで、友人とゲームセンターに行くことが多いのですが、店舗ごとに獲得難易度に差があると感じることがありました。そこで記録を取ることで、難易度の可視化と金額の管理ができ、ユーフォーキャッチャーライフをより楽しむためにこのサービスを開発しました。

■1週間辺りの開発に向けられる時間
- 1週間あたり：56時間

（ストーリポイント1消費するのに2時間を目安として、1週間あたりどれだけストーリポイントを消化できるか確認してください）

■ProjectsのURL
[(https://github.com/users/HIGASHI-SHIHO-54B/projects/1)](https://github.com/users/HIGASHI-SHIHO-54B/projects/1)

■MVPリリースまで
- [ ] rails new
- [ ] Herokuにデプロイ
- [ ] ユーザー登録機能
- [ ] ログイン機能
- [ ] ログアウト機能
- [ ] 獲得グッズ登録機能（画像投稿含む）
- [ ] 獲得グッズ一覧機能
- [ ] 獲得グッズ編集機能
- [ ] 獲得グッズ削除機能
- [ ] プロフィール閲覧
- [ ] プロフィール編集

■MVP後
- [ ] トップページ
- [ ] パスワード変更機能
- [ ] メールアドレス変更機能
- [ ] タグ付け
- [ ] 検索欄

■MVPレビュー依頼予定日
予定日：2024年 11月 15日

**Comment by tmtkzk0823** [comment]
ご提出ありがとうございます。
以下、コメントです。

---

ログイン機能のissueはありますが、ログアウト機能のissueが見受けられなかったのでご確認をお願いします。

**Comment by HIGASHI-SHIHO-54B** [comment]
変更いたしました。よろしくお願いします。

**Comment by kenchasonakai** [comment]
LGTMです！
